// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUtFxVW_ep12H7MJ-Qr1M72RzIygVSA8s',
    appId: '1:389190829565:web:7fb480c2cc7ae51be84594',
    messagingSenderId: '389190829565',
    projectId: 'gen-lang-client-0559167490',
    authDomain: 'gen-lang-client-0559167490.firebaseapp.com',
    storageBucket: 'gen-lang-client-0559167490.firebasestorage.app',
    measurementId: 'G-D05J0W1FNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmrQ3iA6Qrg4fvTTpFJN8Wcm0xhPmiFpQ',
    appId: '1:389190829565:android:9e53265a8df31008e84594',
    messagingSenderId: '389190829565',
    projectId: 'gen-lang-client-0559167490',
    storageBucket: 'gen-lang-client-0559167490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6BK15hoiefSKNcyE7IKqLmqXhcsPxmE',
    appId: '1:389190829565:ios:78f649931da8b945e84594',
    messagingSenderId: '389190829565',
    projectId: 'gen-lang-client-0559167490',
    storageBucket: 'gen-lang-client-0559167490.firebasestorage.app',
    iosBundleId: 'com.example.pentagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE6BK15hoiefSKNcyE7IKqLmqXhcsPxmE',
    appId: '1:389190829565:ios:78f649931da8b945e84594',
    messagingSenderId: '389190829565',
    projectId: 'gen-lang-client-0559167490',
    storageBucket: 'gen-lang-client-0559167490.firebasestorage.app',
    iosBundleId: 'com.example.pentagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUtFxVW_ep12H7MJ-Qr1M72RzIygVSA8s',
    appId: '1:389190829565:web:8bd06c0bc42952b6e84594',
    messagingSenderId: '389190829565',
    projectId: 'gen-lang-client-0559167490',
    authDomain: 'gen-lang-client-0559167490.firebaseapp.com',
    storageBucket: 'gen-lang-client-0559167490.firebasestorage.app',
    measurementId: 'G-0F93B10M8C',
  );

}